# Generated by Django 5.1.15 on 2026-06-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('rating', models.CharField(default='U', max_length=10)),
                ('user_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('poster_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cast', models.JSONField(default=list)),
                ('release_date', models.DateField()),
                ('category', models.CharField(default='Action', max_length=255)),
                ('language', models.CharField(default='English', max_length=100)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('screen_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.PositiveIntegerField(default=1)),
                ('show_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater')),
            ],
        ),
    ]
